### ISSUE TITLE
Dark variant?

### ISSUE THREAD

**Issue by GammaGames** [76784/Daobeam#1]
I love the concept and how the theme was designed, but it's too bright! Are there plans for a dark variant?

**Comment by 76784** [comment]
Thanks very much. I can see where it would be called "bright" compared to any theme with a dark background. But although it has a non-dark background, it's meant to be a light theme that is comfortable to use.

I'll consider doing a dark variant, though. A good dark theme is Zenburn (on VS Code, the Ryan Olson one is the better one, in my opinion - it stays true to the original Zenburn colors when it was first done for Vim). Zenburn is good because it's low contrast (like Daobeam). But I think Zenburn has room for improvement in it's foreground colors, because Vim wasn't really used for CSS and HTML (I don't believe), so it would be nice to have a low contrast dark theme with some of the Daobeam concepts.

**Comment by GammaGames** [comment]
Thank you, I'll check out zenburn in the meantime! At a small glance I think you're right that the foreground colors could be improved, as well. Thank you for the response!
